# Generated by Django 5.2.4 on 2025-08-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estatura (cm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/users/'),
        ),
    ]
