# Generated by Django 5.2.4 on 2025-08-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_city_user_height_user_weight_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número telefónico'),
        ),
    ]
