# Generated by Django 4.2.23 on 2025-08-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='talla',
            field=models.CharField(max_length=20),
        ),
    ]
