# Generated by Django 4.2.23 on 2025-08-10 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_product_discounted_price'),
        ('carrito', '0001_initial'),
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraReferida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='completada', max_length=20)),
                ('carrito_historial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrito.carritohistorial')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_generadas', to='influencer.influencerprofile')),
                ('productos', models.ManyToManyField(to='products.product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_referidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
