# Generated by Django 4.2.23 on 2025-08-10 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencer', '0002_comprareferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprareferida',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comprareferida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras_referidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
