# Generated by Django 4.2.23 on 2025-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_comprareferida_email_alter_comprareferida_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
