# Generated by Django 4.2.23 on 2025-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_influencerprofile_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprareferida',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
