# Generated by Django 4.2.23 on 2025-08-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritohistorial',
            name='cupon_code',
            field=models.CharField(blank=True, help_text='Cupón de descuento usado, si aplica.', max_length=32, null=True),
        ),
    ]
