# Generated by Django 4.2.23 on 2025-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_carritohistorial_cupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritohistorialitem',
            name='talla',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
