# Generated by Django 4.2.23 on 2025-09-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carritohistorialitem_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritohistorial',
            name='total_pagar',
            field=models.PositiveIntegerField(default=0, help_text='Total a pagar calculado en el carrito.'),
        ),
    ]
